name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to EC2
        env:
          AWS_SSH_KEY_BASE64: ${{ secrets.AWS_SSH_KEY_BASE64 }}
          USER: ec2-user
          HOST: ${{ secrets.AWS_EC2_HOST }}
          DB_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          DB_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          DB_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ACTIVATION_URL: ${{ secrets.APPLICATION_MAILING_FRONTEND_ACTIVATION_URL }}
          JAR_FILE: target/Students-Payments-Management-0.0.1-SNAPSHOT.jar
        run: |
          echo "$AWS_SSH_KEY_BASE64" | base64 -d > key.pem
          chmod 400 key.pem
          ssh -i key.pem $USER@$HOST << EOF
            echo "SPRING_DATASOURCE_URL=$DB_URL" > /home/$USER/.env
            echo "SPRING_DATASOURCE_USERNAME=$DB_USERNAME" >> /home/$USER/.env
            echo "SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD" >> /home/$USER/.env
            echo "SPRING_MAIL_USERNAME=$MAIL_USERNAME" >> /home/$USER/.env
            echo "SPRING_MAIL_PASSWORD=$MAIL_PASSWORD" >> /home/$USER/.env
            echo "JWT_SECRET=$JWT_SECRET" >> /home/$USER/.env
            echo "APPLICATION_MAILING_FRONTEND_ACTIVATION_URL=$ACTIVATION_URL" >> /home/$USER/.env
            pkill -f 'java -jar'
            nohup java -jar /home/$USER/Students-Payments-Management-0.0.1-SNAPSHOT.jar &
            exit
          EOF
        shell: bash
