name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'openjdk'

      - name: Build with Maven
        run: mvn clean package

      - name: Copy .env to build directory
        run: cp .env target/

      - name: Deploy to EC2
        env:
          AWS_SSH_KEY_BASE64: ${{ secrets.AWS_SSH_KEY_BASE64 }}
          USER: ec2-user
          HOST: ${{ secrets.AWS_EC2_HOST }}
          JAR_FILE: target/Students-Payments-Management-0.0.1-SNAPSHOT.jar
        run: |
          echo "$AWS_SSH_KEY_BASE64" | base64 -d > key.pem
          chmod 400 key.pem
          scp -i key.pem $JAR_FILE $USER@$HOST:/home/$USER/
          scp -i key.pem target/.env $USER@$HOST:/home/$USER/
          ssh -i key.pem $USER@$HOST << 'EOF'
            pkill -f 'java -jar'
            nohup java -jar /home/$USER/Students-Payments-Management-0.0.1-SNAPSHOT.jar &
            exit
          EOF
        shell: bash
